version : '3.8'
services:
  ruoyi-minio:
    container_name: ruoyi-minio
    build:
      context: ./minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    volumes:
      - ./minio/data:/data


  ruoyi-redis:
    container_name: ruoyi-redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/ruoyi/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/ruoyi/redis/redis.conf
  ruoyi-nginx:
    container_name: ruoyi-nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/ruoyi/projects/ruoyi-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - ruoyi-gateway
    links:
      - ruoyi-gateway
  ruoyi-modules-education-admin:
    container_name: ruoyi-modules-education-admin
    build:
      context: ruoyi-vue/modules-education/education-admin
      dockerfile: dockerfile
    ports:
      - "9207:9207"
    volumes:
      - ./ruoyi/uploadPath:/home/ruoyi/uploadPath
