#------------------------老师管理.老师讲义(二级菜单)---------------------------
['老师管理'.'老师讲义']
menuId = 3015
icon = 'product-list'
path = 'teacherClasses'

#-----------老师管理老师讲义 按钮权限------------
['老师管理'.'老师讲义'.'按钮权限'.'查询']
menuId = 3016
perms = 'query'

['老师管理'.'老师讲义'.'按钮权限'.'添加']
menuId = 3017
perms = 'add'

['老师管理'.'老师讲义'.'按钮权限'.'编辑']
menuId = 3018
perms = 'edit'

['老师管理'.'老师讲义'.'按钮权限'.'删除']
menuId = 3019
perms = 'remove'

['老师管理'.'老师讲义'.'按钮权限'.'导入']
menuId = 3020
perms = 'import'

['老师管理'.'老师讲义'.'按钮权限'.'导出']
menuId = 3021
perms = 'export'